before_install:

before_script:
    - mkdir -p vendors
    - wget -nv https://commondatastorage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.3.zip
    - unzip -qd vendors google_appengine_1.9.3.zip
    - pip install -r ./server/requirements.txt -t ./server/server/lib

script:
    - vendors/google_appengine/dev_appserver.py ./server
