language: java

before_install:
    - wget http://services.gradle.org/distributions/gradle-1.9-bin.zip
    - unzip gradle-1.9-bin.zip
    - export GRADLE_HOME=$PWD/gradle-1.9
    - export PATH=$GRADLE_HOME/bin:$PATH

script:
    - cd android/SafeWalk
    - gradle connectedInstrumentTest
