application: optical-sight-386
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /
    script: serv.application
  - url: /request
    script: serv.application
  - url: /request/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}
    script: serv.application 

